### ISSUE TITLE
推荐一个库 https://github.com/marick/Midje

### ISSUE THREAD

**Issue by xingzheone** [jiacai2050/learn_clojure.mp4#4]
我们公司从2013年开始从j2ee全面转向 clojure .  midje 给了很大的帮助. 
尤其是开发的时候 (autotest :filter :xxx) 这个功能,基本上现在所有语言的单元测试中称第一.当之无愧.

**Comment by jiacai2050** [comment]
看了下 https://github.com/marick/Midje/wiki/Repl-tools 里的介绍，没发现什么特殊的地方，在 cider 里面我一样可以只运行上次测试失败的test
