### ISSUE TITLE
你好 Lisp 讲座的课件还有吗  对 Lisp 非常感兴趣 

### ISSUE THREAD

**Issue by wujunze** [jiacai2050/learn_clojure.mp4#5]
https://mp.weixin.qq.com/s/HSgxPPpZhTR-T3EfMd0mrA   

你好 Lisp 讲座的课件还有吗  对 Lisp 非常感兴趣

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/learn_clojure.mp4/blob/master/2017-08-13_sicp-lisp.pdf

**Comment by wujunze** [comment]
OK  TXH @jiacai2050
